version: '2'
services:
    db:
        image: mysql:5.6
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root

    app:
        build: config/app
        ports:
            - "80:80"
            - "443:443"
            - "2222:22"
            - "1080:1080"
        volumes:
            - .:/var/www/ecom
        links:
            - db