version: '2'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/config/nginx/conf.d:/etc/nginx/conf.d
      - ./var/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./var/config/nginx/ssl:/etc/nginx/ssl
    volumes_from:
      - appdata
    depends_on:
      - php
    networks:
      - front
      - back

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - back

  php:
    build:
      context: ./var/config/php
      #args:
      #  PHP_BUILD_VERSION: 5.6
      #  PHP_BUILD_APCU_VERSION: 4.0.10
    volumes:
      - ./var/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./var/config/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./var/config/php/ext-xdebug.ini:/usr/local/etc/php/conf.d/ext-xdebug.ini
      - ./var/config/php/php.d:/usr/local/etc/php/conf.d/custom.d
    volumes_from:
      - appdata
    depends_on:
      - appdata
      - db
      - cache
    user: www-data
    networks:
      - back

  appdata:
    image: alpine:latest
    volumes:
      - .:/var/www/html
      - ./var/config/appdata/startup.sh:/startup.sh
    command: /bin/sh /startup.sh

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - back
    # Dev settings
    ports:
      - "3306:3306"


  cache:
    image: redis:latest
    networks:
      - back

volumes:
  mysqldata:
    driver: local

networks:
  front:
    driver: bridge
  back:
    driver: bridge